export type Bird = {
  id: string;
  id1: string;
  id2: string;
  id3: string;
  name: string;
  common_name: number;
  status: number;
  sex: number;
  hatch_date: number;
  taxonomic_order: number;
  family: number;
  genus: number;
  species: number;
  sub_species: number;
  body_condition: number;
  feather_condition: number;
  breeding_quality: number;
  breeder_info?: string;
  mutations?: string;
  location: string;
  cost?: number;
  market_value?: number;
  list_price?: number;
  sold_price?: number;
  created_at: number;
  pending: boolean;
};
